version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

    # Group packages into shared PR
    groups:
      rails:
        patterns:
          - 'rails'
          - 'action*'
          - 'active*'

      sidekiq:
        patterns:
          - 'sidekiq'
          - 'sidekiq*'

      rubocop:
        patterns:
          - 'rubocop'
          - 'rubocop-*'
      
      feature_tests:
        patterns:
          - 'selenium-webdriver'
          - 'cucumber-rails'
          - 'database_cleaner'
          - 'site_prism'
          - 'axe-core-*'

      aws:
        patterns:
          - 'aws*'

  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

    # Group packages into shared PR
    groups:
      rails:
        patterns:
          - '@rails/*'
          - '@types/rails__ujs'

      lint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - 'stylelint'
          - 'stylelint-*'
          - '@stylistic/*'
          - 'typescript-eslint'
          - '@types/eslint__js'

      scss:
        patterns:
          - 'sass'
          - 'cssnano'
          - 'cssnano-*'
          - 'postcss'
          - 'postcss-*'

      frontend:
        patterns:
          - 'ccs-frontend'
          - 'govuk-frontend'

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
