version: "2"         # required to adjust maintainability checks

checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
