export_management_report:
  cron: '0 3 * * 0'
  class: 'FacilitiesManagement::RM6232::Admin::ManagementReportExportWorker'
  queue: fm

update_bank_holidays:
  cron: '0 3 1 * *'
  class: 'BankHolidaysWorker'
  queue: legacy_default
