name: "Deploy latest code to AWS"

on:
  workflow_call:
    inputs:
      environment:
        description: 'The name of the environment we are deploying to'
        required: true
        type: string

concurrency:
  group: deploy-${{ inputs.environment }}

jobs:
  run-unit-tests:
    uses: ./.github/workflows/unit_tests.yml

  run-feature-tests:
    uses: ./.github/workflows/feature_tests.yml
    with:
      run_all_feature_tests: true

  deploy-to-application:
    runs-on: ubuntu-latest
    needs:
      - run-unit-tests
      - run-feature-tests
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Trigger AWS CodePipeline - main container
        uses: tim-s-ccs/aws-codepipeline-action@v0.1.2
        with:
          aws-region: ${{ secrets.AWS_PIPELINE_REGION }}
          aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
          pipeline-name: ${{ secrets.AWS_PIPELINE_MAIN_NAME }}

  deploy-to-sidekiq:
    runs-on: ubuntu-latest
    needs:
      - run-unit-tests
      - run-feature-tests
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Trigger AWS CodePipeline - sidekiq container
        uses: tim-s-ccs/aws-codepipeline-action@v0.1.2
        with:
          aws-region: ${{ secrets.AWS_PIPELINE_REGION }}
          aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
          pipeline-name: ${{ secrets.AWS_PIPELINE_SIDEKIQ_NAME }}
