name: "Deploy latest code to AWS"

on:
  workflow_call:
    inputs:
      environment:
        description: 'The name of the environment we are deploying to'
        required: true
        type: string
    secrets:
      AWS_PIPELINE_REGION:
        description: 'The AWS pipeline region'
        required: true
      AWS_PIPELINE_ACCESS_KEY:
        description: 'The AWS pipeline access region'
        required: true
      AWS_PIPELINE_SECRET_KEY:
        description: 'The AWS pipeline secret region'
        required: true
      AWS_PIPELINE_MAIN_NAME:
        description: 'The AWS main pipeline name'
        required: true
      AWS_PIPELINE_SIDEKIQ_NAME:
        description: 'The AWS sidekiq pipeline name'
        required: true

concurrency:
  group: deploy-${{ inputs.environment }}

jobs:
  run-ci:
    uses: ./.github/workflows/ci.yml

  deploy-to-application:
    runs-on: ubuntu-latest
    needs:
      - run-ci
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Trigger AWS CodePipeline - main container
        uses: Crown-Commercial-Service/ccs-aws-codepipeline-action@v1.1.5
        with:
          aws-region: ${{ secrets.AWS_PIPELINE_REGION }}
          aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
          pipeline-name: ${{ secrets.AWS_PIPELINE_MAIN_NAME }}

  deploy-to-sidekiq:
    runs-on: ubuntu-latest
    needs:
      - run-ci
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Trigger AWS CodePipeline - sidekiq container
        uses: Crown-Commercial-Service/ccs-aws-codepipeline-action@v1.1.5
        with:
          aws-region: ${{ secrets.AWS_PIPELINE_REGION }}
          aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
          pipeline-name: ${{ secrets.AWS_PIPELINE_SIDEKIQ_NAME }}
