name: "Run application feature tests"

on:
  workflow_call:

jobs:
  feature-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - crown-marketplace
          - facilities-management

    services:
      postgres:
        image: postgis/postgis:15-3.5-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
          LC_COLLATE: C
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgis://rails:password@localhost:5432/rails_test"
      CUCUMBER_FORMAT: progress

    steps:
      - name: Setup Gecko driver
        uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.254.0
        with:
          bundler-cache: true

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18

      - name: Set up database schema
        run: bin/rails db:test:prepare

      - name: Compile assets
        run: bin/rails assets:precompile

      - name: Seed DB with test data
        run: bin/rails db:static

      - name: Run feature tests for ${{ matrix.service }}
        run: bin/rails cucumber:${{ matrix.service }}
