name: "Run application feature tests"

on:
  workflow_call:

jobs:
  feature-test:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgis/postgis:14-3.4
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgis://rails:password@localhost:5432/rails_test"
      CUCUMBER_FORMAT: progress

    steps:
      - name: Setup Gecko driver
        uses: browser-actions/setup-geckodriver@latest

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.213.0
        with:
          bundler-cache: true

      - name: Set up database schema
        run: bin/rails db:test:prepare

      - name: Compile assets
        run: bin/rails assets:precompile

      - name: Seed DB with test data
        run: bin/rails db:static

      - name: Run all feature tests
        run: bin/rails cucumber:ok
