name: "Ruby on Rails CI"

on:
  push:
    branches-ignore:
      - develop
      - master
      - preview
      - production
  pull_request:

jobs:
  run-unit-tests:
    uses: ./.github/workflows/unit_tests.yaml

  run-feature-tests:
    uses: ./.github/workflows/feature_tests.yaml
    with:
      run_all_feature_tests: ${{ github.event.pull_request.base.ref == 'preview' || github.event.pull_request.base.ref == 'production' }}
