name: "Ruby on Rails CI"

on:
  push:
    branches-ignore:
      - develop
      - master
      - preview
      - production
  pull_request:

jobs:
  run-unit-tests:
    uses: ./.github/workflows/unit_tests.yml
    with:
      publish_test_report: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master' }}
    secrets:
      cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}

  run-feature-tests:
    uses: ./.github/workflows/feature_tests.yml
    with:
      run_all_feature_tests: ${{ github.event.pull_request.base.ref == 'preview' || github.event.pull_request.base.ref == 'production' }}
