name: "Run application unit tests"

on:
  workflow_call:
    inputs:
      publish_test_report:
        description: 'A trigger to publish the test report'
        default: false
        required: false
        type: boolean
    secrets:
      cc_test_reporter_id:
        description: 'The code climate test report ID'
        required: false

jobs:
  unit-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:14-3.4
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgis://rails:password@localhost:5432/rails_test"
      CC_TEST_REPORTER_ID: ${{ secrets.cc_test_reporter_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.241.0
        with:
          bundler-cache: true

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.13

      - name: Set up database schema
        run: bin/rails db:test:prepare

      - name: Compile assets
        run: bin/rails assets:precompile

      - name: Run unit tests
        run: bin/rake

      - name: publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        with:
          debug: true
        if: ${{ inputs.publish_test_report }}
